### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Markowde3jani** [TomDra/Auto-Reddit-Insta-Uploader#1]
Traceback (most recent call last):
  File "C:\Users\amine\Desktop\Auto-Reddit-Downloader-and-Insta-Uploader-main\main.py", line 48, in <module>
    file = random.choice(files)
  File "C:\Users\amine\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\amine\Desktop\Auto-Reddit-Downloader-and-Insta-Uploader-main\main.py", line 62, in <module>
    os.rename(f'images/temp/{file}','images/used/error/'+file)
NameError: name 'file' is not defined. Did you mean: 'files'?

**Comment by TomDra** [comment]
Hi,
Some things you can try:
Make sure your client_id and client_secret from Reddit are correct.
Make sure you are using a valid subreddit.
I have only been able to install the required modules in python 3.8.

I have not been able to replicate this issue so I do not know the true cause, but I'm happy to help when I can.

**Comment by Markowde3jani** [comment]
> Hi, Some things you can try: Make sure your client_id and client_secret from Reddit are correct. Make sure you are using a valid subreddit. I have only been able to install the required modules in python 3.8.
> 
> I have not been able to replicate this issue so I do not know the true cause, but I'm happy to help when I can.

ok i will try on 3.8 version and let u know thanks

**Comment by TomDra** [comment]
> > Hi, Some things you can try: Make sure your client_id and client_secret from Reddit are correct. Make sure you are using a valid subreddit. I have only been able to install the required modules in python 3.8.
> > I have not been able to replicate this issue so I do not know the true cause, but I'm happy to help when I can.
> 
> ok i will try on 3.8 version and let u know thanks

Did that work for you?
